name: laundary_app
description: "app for maa laundry"
publish_to: "none"
version: 1.0.0+15

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # auth and cloud database
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  firebase_database: ^11.3.7
  cloud_firestore: ^5.0.0
  google_sign_in: ^6.1.5
  firebase_messaging: ^15.2.10

  # icons and formatting
  font_awesome_flutter: ^10.7.0
  intl: ^0.18.0

  # state management and persistent data
  get: ^4.7.2
  get_storage: ^2.1.1

  # local database
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.9.0

  # to launch urls
  url_launcher: ^6.2.5
  http: ^1.2.0
  qr_flutter: ^4.1.0
  flutter_hooks: ^0.21.3+1

  # to show date pickers
  syncfusion_flutter_datepicker: ^24.1.41

  #for checking interner connection
  connectivity_plus: ^7.3.1
  internet_connection_checker_plus: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/decoration/
    - assets/logos/
    - assets/illustrations/
    - assets/images/
  
  fonts:
    - family: DynaPuff
      fonts:
        - asset: assets/fonts/DynaPuff-Regular.ttf
        - asset: assets/fonts/DynaPuff-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 700
    - family: Kaushan
      fonts:
        - asset: assets/fonts/Kaushan-Regular.ttf
          weight: 700


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
